create table medico(id number generated by default as identity primary key,
        nome varchar2(100),
        crm varchar2(10),
        especialidade varchar2(50));
        
        
create table paciente(id number generated by default as identity primary key,
        nome varchar2(100),
        convenio varchar2(50));
        
create table consulta(id number  generated by default as identity primary key,
        data date,
        horario varchar2(15),
        paciente_id number,
        medico_id number
);
        

insert into medico(nome, especialidade,crm) values('Maria Fernanda Pinto','psiquiatria', '71579');
insert into medico(nome, especialidade,crm) values('Evelyn Teixeira','ortopedia', '71768');
insert into medico(nome, especialidade,crm) values('Ana Clara Ribeiro','endocrinologia', '75269');
insert into medico(nome, especialidade,crm) values('Diego Gomes','cirurgia', '74381');
insert into medico(nome, especialidade,crm) values('Matheus Correia','psiquiatra', '58771');
insert into medico(nome, especialidade,crm) values('Camila Ramos','ortopedista', '65349');
insert into medico(nome, especialidade,crm) values('Marcelo Teixeira','endocrinologia', '60215');
insert into medico(nome, especialidade,crm) values('Maysa da Conceição','cirurgia', '64081');
insert into medico(nome, especialidade,crm) values('Isabelly Farias','ortopedia', '78648');
insert into medico(nome, especialidade,crm) values('Maria Clara Freitas','endocrinologia', '70781');
insert into medico(nome, especialidade,crm) values('Esther Aragao','cirurgia', '56259');
insert into medico(nome, especialidade,crm) values('Andre Jesus','psiquiatria', '72080');
insert into medico(nome, especialidade,crm) values('Clarice Correia','ortopedista', '55658');
insert into medico(nome, especialidade,crm) values('Joao Pedro da Rosa','endocrinologia', '78925');
insert into medico(nome, especialidade,crm) values('Evelyn Goncalves','cirurgia', '65673');
insert into medico(nome, especialidade,crm) values('Igor da Paz','psiquiatria', '74202');
insert into medico(nome, especialidade,crm) values('Maysa Sales','ortopedia', '72623');
insert into medico(nome, especialidade,crm) values('Caua Porto','endocrinologia', '71350');
insert into medico(nome, especialidade,crm) values('Luiza Vieira','cirurgia', '56914');
insert into paciente(nome, convenio) values('Caue Jesus', 'Notre Dame');
insert into paciente(nome, convenio) values('Miguel Almeida', 'Bradesco');
insert into paciente(nome, convenio) values('Mariana da Costa', 'Sul America');
insert into paciente(nome, convenio) values('Ana Livia Freitas', 'Care Plus');
insert into paciente(nome, convenio) values('Gabrielly Porto', 'Porto Seguro');
insert into paciente(nome, convenio) values('Joao Pedro Novaes', 'Notre Dame');
insert into paciente(nome, convenio) values('Lucas Gabriel Nascimento', 'Bradesco');
insert into paciente(nome, convenio) values('Benicio Fogaca', 'Sul America');
insert into paciente(nome, convenio) values('Carlos Eduardo da Luz', 'Care Plus');
insert into paciente(nome, convenio) values('Davi Luiz Aragao', 'Porto Seguro');
insert into paciente(nome, convenio) values('Nicole da Mota', 'Notre Dame');
insert into paciente(nome, convenio) values('Valentina Oliveira', 'Bradesco');
insert into paciente(nome, convenio) values('Eduardo Pinto', 'Sul America');
insert into paciente(nome, convenio) values('Joao Pedro Araujo', 'Care Plus');
insert into paciente(nome, convenio) values('Amanda Nogueira', 'Porto Seguro');
insert into paciente(nome, convenio) values('Manuela Novaes', 'Notre Dame');
insert into paciente(nome, convenio) values('Beatriz da Mota', 'Bradesco');
insert into paciente(nome, convenio) values('Isadora da Mata', 'Sul America');
insert into paciente(nome, convenio) values('Lorena Viana', 'Care Plus');
insert into paciente(nome, convenio) values('Gustavo Araujo', 'Porto Seguro');
insert into paciente(nome, convenio) values('Pedro Lucas Monteiro', 'Notre Dame');
insert into paciente(nome, convenio) values('Maria Luiza Mendes', 'Bradesco');
insert into paciente(nome, convenio) values('Daniela Freitas', 'Sul America');
insert into paciente(nome, convenio) values('Isabel Almeida', 'Care Plus');
insert into paciente(nome, convenio) values('Francisco Monteiro', 'Porto Seguro');
insert into paciente(nome, convenio) values('Maria Sophia da Conceiçao', 'Notre Dame');
insert into paciente(nome, convenio) values('Vitoria Lopes', 'Bradesco');
insert into paciente(nome, convenio) values('Juan Novaes', 'Sul America');
insert into paciente(nome, convenio) values('Sophia Silva', 'Care Plus');
insert into paciente(nome, convenio) values('Daniel da Costa', 'Porto Seguro');